# Generated by Django 4.2.6 on 2023-10-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=107)),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
